<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ankit" ignored="0" name="Test" tests="6" failures="2" timestamp="22 Mar 2020 13:05:11 GMT" time="27.195" errors="0">
  <testcase name="testSuccess" time="23.842" classname="com.extentreport.Demo2"/>
  <testcase name="Method1Demo3" time="0.008" classname="com.extentreport.Demo3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.extentreport.Demo3.Method1Demo3(Demo3.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Method1Demo3 -->
  <testcase name="testFailed" time="0.0" classname="com.extentreport.Demo2">
    <failure type="java.lang.AssertionError" message="Executing Failed Test Case">
      <![CDATA[java.lang.AssertionError: Executing Failed Test Case
at com.extentreport.Demo2.testFailed(Demo2.java:57)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase name="Method2Demo3" time="0.0" classname="com.extentreport.Demo3"/>
  <testcase name="testSkipped" time="0.004" classname="com.extentreport.Demo2">
    <skipped/>
  </testcase> <!-- testSkipped -->
  <testcase name="Method3Demo3" time="0.0" classname="com.extentreport.Demo3">
    <skipped/>
  </testcase> <!-- Method3Demo3 -->
</testsuite> <!-- Test -->
